DEFAULT_MAX_RRT_ITERATIONS = -1
DEFAULT_NUM_OPTIMIZATIONS = 0
K = 20

NUM_WALL_ANGLE_SAMPLES = 20

from FinalChallengePy.CarConstants import *

FAKE_WALL_EXTENSION = CAR_WIDTH/2. + CONE_WIDTH
FAKE_WALL_BUFFER = FAKE_WALL_EXTENSION + 0.2
